# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: pretty

# Setup
title: Gotz.co
url: https://gotz.co
description: "Network Automation Consultant with a background in utilities and ISPs"
title_image: "https://gotz.co/public/favicon.ico"
twitter_username: nlgotz
paginate: 1
baseurl: "/"

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir: _sass
  style: compressed

# About/contact
author:
  name: Nate Gotz
  url: https://twitter.com/nlgotz

# Custom vars
version: 1.0.0
github:
  repo: https://github.com/nlgotz/nlgotz.github.com

pages_list:
  About: "/about"
  Archive: "/archive"
  Feed: "/atom.xml"

plugins: [jekyll-paginate]
